<a href="https://colab.research.google.com/github/CaspianH-2025/data-science-toolkit/blob/main/Tutorial_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr_2x2 = np.array([[1, 2], [3, 4]])
print(arr_2x2)

[[1 2]
 [3 4]]


In [5]:
rand_3x4 = np.random.rand(3, 4)
print(rand_3x4)

[[0.56302026 0.50233002 0.83335779 0.74446042]
 [0.57926326 0.1099911  0.4856864  0.23010631]
 [0.62117772 0.06549049 0.49078248 0.42394911]]


In [6]:
ones_4 = np.ones((2, 3))
zeros_4 = np.zeros((3, 2))
print(ones_4)
print(zeros_4)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
rand_6x3 = np.random.rand(6, 3)
transposed = rand_6x3.T
print(rand_6x3)
print(transposed)

[[0.15801739 0.01004035 0.58021151]
 [0.44648475 0.43019102 0.47457257]
 [0.10931839 0.55025786 0.48091064]
 [0.87240599 0.34703401 0.80058446]
 [0.46848769 0.491069   0.0938988 ]
 [0.45467888 0.16961185 0.86591654]]
[[0.15801739 0.44648475 0.10931839 0.87240599 0.46848769 0.45467888]
 [0.01004035 0.43019102 0.55025786 0.34703401 0.491069   0.16961185]
 [0.58021151 0.47457257 0.48091064 0.80058446 0.0938988  0.86591654]]


In [8]:
n, p, m = 2, 3, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = A @ B
print(A)
print(B)
print(dot_product)

[[0.60482655 0.20071766 0.88639767]
 [0.01379711 0.31539542 0.0829885 ]]
[[0.41061107 0.6719358  0.65518952 0.92048761]
 [0.71318366 0.14195445 0.90566807 0.73781749]
 [0.09950521 0.44201229 0.27018868 0.8287814 ]]
[[0.47969821 0.82669604 0.81755421 1.43945825]
 [0.23885789 0.09072449 0.31710583 0.31418365]]
